name: Test

on:
  pull_request:
    branches:
      - "**"

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["16.17.0"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Check licenses
        run: npm run license-check

      - name: Run unit tests
        run: npm run test
